name: Build

on:
  pull_request:
    branches: [ 'main*', 'instrumentation*', 'exporter*', 'extensions*' ]

jobs:
  detect-changes:
    runs-on: windows-latest
    outputs:
      changes: ${{ steps.changes.outputs.changes }}
    steps:
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          md: [ '**.md' ]
          build: ['build/**']
          shared: ['src/Shared/**']
          wcf: ['*/OpenTelemetry.Instrumentation.Wcf*/**', 'examples/wcf/**', '!**.md']
          solution: [
            'src/**',
            'test/**',
            'examples/**',
            '!*/OpenTelemetry.Instrumentation.Wcf*/**',
            '!examples/wcf/**',
            '!**.md'
            ]

  lint-md:
    needs: detect-changes
    if: contains(needs.detect-changes.outputs.changes, 'md')
    runs-on: ubuntu-latest

    steps:
    - name: check out code
      uses: actions/checkout@v4

    - name: install markdownlint-cli
      run: sudo npm install -g markdownlint-cli

    - name: run markdownlint
      run: markdownlint .

  build-test-solution:
    needs: detect-changes
    if: |
      contains(needs.detect-changes.outputs.changes, 'solution')
      || contains(needs.detect-changes.outputs.changes, 'build')
      || contains(needs.detect-changes.outputs.changes, 'shared')

    strategy:
      fail-fast: false # ensures the entire test matrix is run, even if one permutation fails
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        version: [ net462, net6.0, net7.0 ]
        exclude:
        - os: ubuntu-latest
          version: net462

    runs-on: ${{ matrix.os }}
    steps:
    - run: echo testing

  build-test-wcf:
    needs: detect-changes
    if: |
      contains(needs.detect-changes.outputs.changes, 'wcf')
      || contains(needs.detect-changes.outputs.changes, 'build')
      || contains(needs.detect-changes.outputs.changes, 'shared')
    uses: ./.github/workflows/Component.BuildTest.yml
    with:
      project-name: OpenTelemetry.Instrumentation.Wcf
      code-cov-name: Instrumentation.Wcf

  build-test:
    needs: [detect-changes, lint-md, build-test-solution, build-test-wcf]
    runs-on: windows-latest
    steps:
    - run: echo build complete ✓
