name: Build

on:
  pull_request:
    branches: [ 'main*', 'instrumentation*', 'exporter*', 'extensions*' ]

jobs:
  lint-mispell-sanitycheck:
    uses: ./.github/workflows/sanitycheck.yml

  detect-changes:
    runs-on: windows-latest
    outputs:
      changes: ${{ steps.changes.outputs.changes }}
    steps:
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          md: [ '**.md' ]
          build: ['build/**']
          shared: ['src/Shared/**']
          code: ['**.cs', '.editorconfig']
          redis: ['*/OpenTelemetry.Instrumentation.StackExchangeRedis*/**', 'examples/redis/**', '!**.md']
          wcf: ['*/OpenTelemetry.Instrumentation.Wcf*/**', 'examples/wcf/**', '!**.md']
          solution: [
            'src/**',
            'test/**',
            'examples/**',
            '!*/OpenTelemetry.Instrumentation.Wcf*/**',
            '!examples/wcf/**',
            '!**.md'
            ]

  lint-md:
    needs: detect-changes
    if: contains(needs.detect-changes.outputs.changes, 'md')
    uses: ./.github/workflows/markdownlint.yml

  lint-dotnet-format:
    needs: detect-changes
    if: contains(needs.detect-changes.outputs.changes, 'code')
    uses: ./.github/workflows/dotnet-format.yml

  build-test-solution:
    needs: detect-changes
    if: |
      contains(needs.detect-changes.outputs.changes, 'solution')
      || contains(needs.detect-changes.outputs.changes, 'shared')
    # || contains(needs.detect-changes.outputs.changes, 'build')

    runs-on: windows-latest
    steps:
    - run: echo testing

  build-test-wcf:
    needs: detect-changes
    if: |
      contains(needs.detect-changes.outputs.changes, 'wcf')
      || contains(needs.detect-changes.outputs.changes, 'build')
      || contains(needs.detect-changes.outputs.changes, 'shared')
    uses: ./.github/workflows/Component.BuildTest.yml
    with:
      project-name: OpenTelemetry.Instrumentation.Wcf
      code-cov-name: Instrumentation.Wcf

  integration-test-redis:
    needs: detect-changes
    if: |
      contains(needs.detect-changes.outputs.changes, 'redis')
      || contains(needs.detect-changes.outputs.changes, 'build')
      || contains(needs.detect-changes.outputs.changes, 'shared')
    uses: ./.github/workflows/integration.yml

  build-test:
    needs: [
      lint-mispell-sanitycheck,
      detect-changes,
      lint-md,
      lint-dotnet-format,
      build-test-solution,
      build-test-wcf,
      integration-test-redis
      ]
    if: always() && !cancelled() && !contains(needs.*.result, 'failure')
    runs-on: windows-latest
    steps:
    - run: echo 'build complete ✓'
