name: Integration Build OpenTelemetry.Instrumentation.StackExchangeRedis

on:
  workflow_call:
    inputs:
      job:
        required: true
        type: string

jobs:
  redis-integration-test:
    if: inputs.job == 'all' || inputs.job == 'redis-integration-test'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version: [net8.0]
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Run redis docker compose
        run: docker compose --file=test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/docker-compose.yml --file=build/docker-compose.${{ matrix.version }}.yml --project-directory=. up --exit-code-from=tests --build

  kafka-integration-test:
    if: inputs.job == 'all' || inputs.job == 'kafka-integration-test'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version: [net8.0]
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Run kafka docker compose
        run: docker compose --file=test/OpenTelemetry.Instrumentation.ConfluentKafka.Tests/docker-compose.yml --file=build/docker-compose.${{ matrix.version }}.yml --project-directory=. up --exit-code-from=tests --build
