name: Lint - Markdown

on:
  workflow_call:

jobs:
  run-markdownlint:
    runs-on: ubuntu-22.04

    steps:
    - name: check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: run markdownlint
      uses: DavidAnson/markdownlint-cli2-action@6b51ade7a9e4a75a7ad929842dd298a3804ebe8b # v23.1.0
      with:
        globs: |
          **/*.md
          !.github/**/*.md
