name: Lint - Markdown

on:
  workflow_call:

jobs:
  run-markdownlint:
    runs-on: ubuntu-22.04

    steps:
    - name: check out code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: run markdownlint
      uses: DavidAnson/markdownlint-cli2-action@05f32210e84442804257b2a6f20b273450ec8265 # v19.1.0
      with:
        globs: |
          **/*.md
          !.github/**/*.md
