name: Lint - Markdown

on:
  workflow_call:

jobs:
  run-markdownlint:
    runs-on: ubuntu-22.04

    steps:
    - name: check out code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: run markdownlint
      uses: DavidAnson/markdownlint-cli2-action@05f32210e84442804257b2a6f20b273450ec8265 # v19.1.0
      with:
        globs: |
          **/*.md
          !.github/**/*.md
