name: Pack OpenTelemetry.Sampler.AWS

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Sampler.AWS-*' # trigger when we create a tag with prefix "Sampler.AWS-"

jobs:
  call-build-test-pack:
    uses: ./.github/workflows/Component.Package.yml
    with:
      project: src/OpenTelemetry.Sampler.AWS/OpenTelemetry.Sampler.AWS.csproj
    secrets: inherit
