name: Pack OpenTelemetry.Extensions.AWS

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Extensions.AWS-*' # trigger when we create a tag with prefix "Extensions.AWS-"

jobs:
  call-build-test-pack:
    uses: ./.github/workflows/Component.Package.yml
    with:
      project: src/OpenTelemetry.Extensions.AWS/OpenTelemetry.Extensions.AWS.csproj
    secrets: inherit
