name: Pack OpenTelemetry.Instrumentation.Cassandra

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Instrumentation.Cassandra-*'

jobs:
  call-build-test-pack:
    uses: ./.github/workflows/Component.Package.yml
    with:
      project: src/OpenTelemetry.Instrumentation.Cassandra/OpenTelemetry.Instrumentation.Cassandra.csproj
    secrets: inherit
