name: Pack OpenTelemetry.Resources.Process

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Resources.Process-*' # trigger when we create a tag with prefix "Resources.Process-"

jobs:
  call-build-test-pack:
    uses: ./.github/workflows/Component.Package.yml
    with:
      project: build/Projects/OpenTelemetry.Resources.Process.proj
    secrets: inherit
