name: Pack OpenTelemetry.Instrumentation.ElasticsearchClient

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Instrumentation.ElasticsearchClient-*' # trigger when we create a tag with prefix "Instrumentation.ElasticsearchClient-"

jobs:
  call-build-test-pack:
    uses: ./.github/workflows/Component.Package.yml
    with:
      project: src/OpenTelemetry.Instrumentation.ElasticsearchClient/OpenTelemetry.Instrumentation.ElasticsearchClient.csproj
    secrets: inherit
