name: Pack OpenTelemetry.Instrumentation.Wcf

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Instrumentation.Wcf-*' # trigger when we create a tag with prefix "Instrumentation.Wcf-"

jobs:
  call-build-test-pack:
    uses: ./.github/workflows/Component.Package.yml
    with:
      project: build/Projects/OpenTelemetry.Instrumentation.Wcf.proj
    secrets: inherit
