name: Pack OpenTelemetry.Instrumentation.AWSLambda

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Instrumentation.AWSLambda-*' # trigger when we create a tag with prefix "Instrumentation.AWSLambda-"

jobs:
  call-build-test-pack:
    uses: ./.github/workflows/Component.Package.yml
    with:
      project: src/OpenTelemetry.Instrumentation.AWSLambda/OpenTelemetry.Instrumentation.AWSLambda.csproj
    secrets: inherit
