name: Pack OpenTelemetry.Instrumentation.GrpcCore

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Instrumentation.GrpcCore-*' # trigger when we create a tag with prefix "Instrumentation.GrpcCore-"

jobs:
  call-build-test-pack:
    uses: ./.github/workflows/Component.Package.yml
    with:
      project: src/OpenTelemetry.Instrumentation.GrpcCore/OpenTelemetry.Instrumentation.GrpcCore.csproj
    secrets: inherit
