name: Pack OpenTelemetry.Exporter.Instana

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Exporter.Instana-*' # trigger when we create a tag with prefix "Exporter.Instana-"

jobs:
  call-build-test-pack:
    uses: ./.github/workflows/Component.Package.yml
    with:
      project: src/OpenTelemetry.Exporter.Instana/OpenTelemetry.Exporter.Instana.csproj
    secrets: inherit
