name: Pack OpenTelemetry.ResourceDetectors.AWS

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'ResourceDetectors.AWS-*' # trigger when we create a tag with prefix "ResourceDetectors.AWS-"

jobs:
  call-build-test-pack:
    uses: ./.github/workflows/Component.Package.yml
    with:
      project: src/OpenTelemetry.ResourceDetectors.AWS/OpenTelemetry.ResourceDetectors.AWS.csproj
    secrets: inherit
