name: Pack OpenTelemetry.Exporter.InfluxDB

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Exporter.InfluxDB-*' # trigger when we create a tag with prefix "Exporter.InfluxDB-"

jobs:
  call-build-test-pack:
    uses: ./.github/workflows/Component.Package.yml
    with:
      project: src/OpenTelemetry.Exporter.InfluxDB/OpenTelemetry.Exporter.InfluxDB.csproj
    secrets: inherit
