name: Pack OpenTelemetry.Instrumentation.EntityFrameworkCore

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Instrumentation.EntityFrameworkCore-*' # trigger when we create a tag with prefix "Instrumentation.EntityFrameworkCore-"

jobs:
  call-build-test-pack:
    uses: ./.github/workflows/Component.Package.yml
    with:
      project: src/OpenTelemetry.Instrumentation.EntityFrameworkCore/OpenTelemetry.Instrumentation.EntityFrameworkCore.csproj
    secrets: inherit
