name: Pack OpenTelemetry.Instrumentation.Hangfire

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Instrumentation.Hangfire-*' # trigger when we create a tag with prefix "Instrumentation.Hangfire-"

jobs:
  call-build-test-pack:
    uses: ./.github/workflows/Component.Package.yml
    with:
      project: src/OpenTelemetry.Instrumentation.Hangfire/OpenTelemetry.Instrumentation.Hangfire.csproj
    secrets: inherit
