name: Pack OpenTelemetry.ResourceDetectors.Container

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'ResourceDetectors.Container-*' # trigger when we create a tag with prefix "ResourceDetectors.Container-"

jobs:
  call-build-test-pack:
    uses: ./.github/workflows/Component.Package.yml
    with:
      project: src/OpenTelemetry.ResourceDetectors.Container/OpenTelemetry.ResourceDetectors.Container.csproj
    secrets: inherit
