name: Pack OpenTelemetry.Extensions.Enrichment

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Extensions.Enrichment-*' # trigger when we create a tag with prefix "Extensions.Enrichment-"

jobs:
  call-build-test-pack:
    uses: ./.github/workflows/Component.Package.yml
    with:
      project: src/OpenTelemetry.Extensions.Enrichment/OpenTelemetry.Extensions.Enrichment.csproj
    secrets: inherit
