name: Pack OpenTelemetry.Instrumentation.Quartz

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Instrumentation.Quartz-*' # trigger when we create a tag with prefix "Instrumentation.Quartz-"

jobs:
  call-build-test-pack:
    uses: ./.github/workflows/Component.Package.yml
    with:
      project: src/OpenTelemetry.Instrumentation.Quartz/OpenTelemetry.Instrumentation.Quartz.csproj
    secrets: inherit
