name: Pack OpenTelemetry.Exporter.Stackdriver

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    tags:
      - 'Exporter.Stackdriver-*' # trigger when we create a tag with prefix "Exporter.Stackdriver-"

jobs:
  call-build-test-pack:
    uses: ./.github/workflows/Component.Package.yml
    with:
      project: src/OpenTelemetry.Exporter.Stackdriver/OpenTelemetry.Exporter.Stackdriver.csproj
    secrets: inherit
