name: Lint - Spelling & Encoding

on:
  workflow_call:

jobs:
  run-misspell:
    runs-on: ubuntu-22.04

    steps:
    - name: check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: install misspell
      run: |
        curl -L -o ./install-misspell.sh https://git.io/misspell
        sh ./install-misspell.sh

    - name: run misspell
      run: ./bin/misspell -error .

  run-sanitycheck:
    runs-on: ubuntu-22.04

    steps:
    - name: check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: detect non-ASCII encoding and trailing space
      run: python3 ./build/scripts/sanitycheck.py
