name: Lint - YAML

on:
  workflow_call:
  workflow_dispatch:

jobs:
  run-yamllint:
    runs-on: ubuntu-22.04

    steps:
    - name: check out code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: install yamllint
      run: pip install -r ./build/yamllint-requirements.txt --require-hashes

    - name: run yamllint
      run: yamllint --no-warnings .
