name: Lint - YAML

on:
  workflow_call:
  workflow_dispatch:

jobs:
  run-yamllint:
    runs-on: ubuntu-22.04

    steps:
    - name: check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: install yamllint
      run: pip install -r ./build/yamllint-requirements.txt --require-hashes

    - name: run yamllint
      run: yamllint --no-warnings .
